services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app               # Mount project folder for live reload
      - /app/node_modules    # Prevent overwriting container node_modules      
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - NEXT_PUBLIC_API_BASE_URL=https://api.glst.in
      - NEXT_PUBLIC_PRODUCT_API=/api/v2/product
      - NEXT_PUBLIC_PRODUCT_PRICE_API=/api/v2/get-product-price
      - NEXT_PUBLIC_PRODUCT_DESCRIPTION_API=/api/v1/product-description
      - NEXT_PUBLIC_ACCESS_TOKEN=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiI5MjBjMTIwZS0zY2IwLTQ3OGMtOTY0Yi1hM2ZhZmFjMDFhNGIiLCJqdGkiOiI1MTYwYzgzMTI1NjRiODEzYWQ0MDZmN2UzZDIxYzc1NGI4YWFiNjM5Y2ZmN2MxOGRhN2UwNTc3NDJjZGMyZWZmMWEyY2U4OWU2N2MxYzBjMiIsImlhdCI6MTc1ODk4MDkxNi4wNDcyODUsIm5iZiI6MTc1ODk4MDkxNi4wNDcyOSwiZX
      - REVALIDATION_INTERVAL=3600
      - NEXT_PUBLIC_DEFAULT_CURRENCY=INR
      - NEXT_PUBLIC_MIN_ORDER_QUANTITY=1
      - NEXT_PUBLIC_MAX_ORDER_QUANTITY=999
      - NEXT_PUBLIC_ENABLE_BULK_PRICING=true
      - NEXT_PUBLIC_ENABLE_COD=true
      - NEXT_PUBLIC_DEFAULT_RETURN_PERIOD=7
      - NEXT_PUBLIC_DEFAULT_PROCESSING_DAYS=15
      - NEXT_PUBLIC_DEFAULT_SHIPPING_DAYS=4
    restart: unless-stopped