version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app               # Mount project folder for live reload
      - /app/node_modules    # Prevent overwriting container node_modules      
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production